language: c++

matrix:
  include:
    # GCC builds on Linux
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-zeromq --disable-output-uhd"
      os: linux
      dist: bionic
      sudo: required
      arch: amd64
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - libcurl4-openssl-dev
            - libfftw3-dev
            # libuhd-dev is not allowed
            - g++-9
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-zeromq --disable-output-uhd"
      os: linux
      dist: bionic
      sudo: required
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - libcurl4-openssl-dev
            - libfftw3-dev
            # libuhd-dev is not allowed
            - g++-9

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-output-raw"
      os: linux
      dist: bionic
      sudo: required
      arch: amd64
      compiler: gcc
      addons: *linuxaddons
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-output-raw"
      os: linux
      dist: bionic
      sudo: required
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --disable-native"
      os: linux
      dist: bionic
      sudo: required
      arch: amd64
      compiler: gcc
      addons: *linuxaddons
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --disable-native"
      os: linux
      dist: bionic
      sudo: required
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-trace"
      os: linux
      dist: bionic
      sudo: required
      arch: amd64
      compiler: gcc
      addons: *linuxaddons
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-uhd --enable-trace"
      os: linux
      dist: bionic
      sudo: required
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      addons: *linuxaddons

before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    brew install fftw || true
    brew install uhd || true
    fi

script:
  - |
    ./bootstrap.sh
    ./configure $CONF
    make

